// SPDX-License-Identifier: MIT

package greentic:telegram-webhook@0.0.1;

use greentic:http/client@1.1.0 as http-client;
use greentic:secrets-store/secrets-store@1.0.0;

world telegram-webhook {
  import http-client;
  import secrets-store;
}
