// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod greentic {
        pub mod provider_schema_core {
            /// Minimal provider schema surface for messaging/secrets/events providers.
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod schema_core_api {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                /// Opaque validation result JSON payload.
                pub type ValidationResult = _rt::Vec<u8>;
                /// Opaque health status JSON payload.
                pub type HealthStatus = _rt::Vec<u8>;
                /// Opaque invocation result JSON payload.
                pub type InvokeResult = _rt::Vec<u8>;
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_describe_cabi<T: Guest>() -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::describe();
                    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let vec2 = (result0).into_boxed_slice();
                    let ptr2 = vec2.as_ptr().cast::<u8>();
                    let len2 = vec2.len();
                    ::core::mem::forget(vec2);
                    *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len2;
                    *ptr1.add(0).cast::<*mut u8>() = ptr2.cast_mut();
                    ptr1
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_describe<T: Guest>(arg0: *mut u8) {
                    let l0 = *arg0.add(0).cast::<*mut u8>();
                    let l1 = *arg0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let base2 = l0;
                    let len2 = l1;
                    _rt::cabi_dealloc(base2, len2 * 1, 1);
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_validate_config_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let result1 = T::validate_config(
                        _rt::Vec::from_raw_parts(arg0.cast(), len0, len0),
                    );
                    let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let vec3 = (result1).into_boxed_slice();
                    let ptr3 = vec3.as_ptr().cast::<u8>();
                    let len3 = vec3.len();
                    ::core::mem::forget(vec3);
                    *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len3;
                    *ptr2.add(0).cast::<*mut u8>() = ptr3.cast_mut();
                    ptr2
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_validate_config<T: Guest>(arg0: *mut u8) {
                    let l0 = *arg0.add(0).cast::<*mut u8>();
                    let l1 = *arg0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let base2 = l0;
                    let len2 = l1;
                    _rt::cabi_dealloc(base2, len2 * 1, 1);
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_healthcheck_cabi<T: Guest>() -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::healthcheck();
                    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let vec2 = (result0).into_boxed_slice();
                    let ptr2 = vec2.as_ptr().cast::<u8>();
                    let len2 = vec2.len();
                    ::core::mem::forget(vec2);
                    *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len2;
                    *ptr1.add(0).cast::<*mut u8>() = ptr2.cast_mut();
                    ptr1
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_healthcheck<T: Guest>(arg0: *mut u8) {
                    let l0 = *arg0.add(0).cast::<*mut u8>();
                    let l1 = *arg0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let base2 = l0;
                    let len2 = l1;
                    _rt::cabi_dealloc(base2, len2 * 1, 1);
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_invoke_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                    arg2: *mut u8,
                    arg3: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                    let len1 = arg3;
                    let result2 = T::invoke(
                        _rt::string_lift(bytes0),
                        _rt::Vec::from_raw_parts(arg2.cast(), len1, len1),
                    );
                    let ptr3 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let vec4 = (result2).into_boxed_slice();
                    let ptr4 = vec4.as_ptr().cast::<u8>();
                    let len4 = vec4.len();
                    ::core::mem::forget(vec4);
                    *ptr3.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len4;
                    *ptr3.add(0).cast::<*mut u8>() = ptr4.cast_mut();
                    ptr3
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_invoke<T: Guest>(arg0: *mut u8) {
                    let l0 = *arg0.add(0).cast::<*mut u8>();
                    let l1 = *arg0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let base2 = l0;
                    let len2 = l1;
                    _rt::cabi_dealloc(base2, len2 * 1, 1);
                }
                pub trait Guest {
                    /// Describes the provider manifest as JSON bytes.
                    /// The JSON should at minimum include: `provider_type`, `capabilities`, and `ops`.
                    fn describe() -> _rt::Vec<u8>;
                    /// Validates configuration JSON; returns a JSON payload (opaque to the ABI).
                    fn validate_config(config_json: _rt::Vec<u8>) -> ValidationResult;
                    /// Returns provider health as a JSON payload.
                    fn healthcheck() -> HealthStatus;
                    /// Invokes a provider operation with JSON input, returning JSON output.
                    fn invoke(op: _rt::String, input_json: _rt::Vec<u8>) -> InvokeResult;
                }
                #[doc(hidden)]
                macro_rules! __export_greentic_provider_schema_core_schema_core_api_1_0_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "greentic:provider-schema-core/schema-core-api@1.0.0#describe")]
                        unsafe extern "C" fn export_describe() -> * mut u8 { unsafe {
                        $($path_to_types)*:: _export_describe_cabi::<$ty > () } }
                        #[unsafe (export_name =
                        "cabi_post_greentic:provider-schema-core/schema-core-api@1.0.0#describe")]
                        unsafe extern "C" fn _post_return_describe(arg0 : * mut u8,) {
                        unsafe { $($path_to_types)*:: __post_return_describe::<$ty >
                        (arg0) } } #[unsafe (export_name =
                        "greentic:provider-schema-core/schema-core-api@1.0.0#validate-config")]
                        unsafe extern "C" fn export_validate_config(arg0 : * mut u8, arg1
                        : usize,) -> * mut u8 { unsafe { $($path_to_types)*::
                        _export_validate_config_cabi::<$ty > (arg0, arg1) } } #[unsafe
                        (export_name =
                        "cabi_post_greentic:provider-schema-core/schema-core-api@1.0.0#validate-config")]
                        unsafe extern "C" fn _post_return_validate_config(arg0 : * mut
                        u8,) { unsafe { $($path_to_types)*::
                        __post_return_validate_config::<$ty > (arg0) } } #[unsafe
                        (export_name =
                        "greentic:provider-schema-core/schema-core-api@1.0.0#healthcheck")]
                        unsafe extern "C" fn export_healthcheck() -> * mut u8 { unsafe {
                        $($path_to_types)*:: _export_healthcheck_cabi::<$ty > () } }
                        #[unsafe (export_name =
                        "cabi_post_greentic:provider-schema-core/schema-core-api@1.0.0#healthcheck")]
                        unsafe extern "C" fn _post_return_healthcheck(arg0 : * mut u8,) {
                        unsafe { $($path_to_types)*:: __post_return_healthcheck::<$ty >
                        (arg0) } } #[unsafe (export_name =
                        "greentic:provider-schema-core/schema-core-api@1.0.0#invoke")]
                        unsafe extern "C" fn export_invoke(arg0 : * mut u8, arg1 : usize,
                        arg2 : * mut u8, arg3 : usize,) -> * mut u8 { unsafe {
                        $($path_to_types)*:: _export_invoke_cabi::<$ty > (arg0, arg1,
                        arg2, arg3) } } #[unsafe (export_name =
                        "cabi_post_greentic:provider-schema-core/schema-core-api@1.0.0#invoke")]
                        unsafe extern "C" fn _post_return_invoke(arg0 : * mut u8,) {
                        unsafe { $($path_to_types)*:: __post_return_invoke::<$ty > (arg0)
                        } } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_greentic_provider_schema_core_schema_core_api_1_0_0_cabi;
                #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<
                        u8,
                    >; 2 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 2
                        * ::core::mem::size_of::<*const u8>()],
                );
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    pub use alloc_crate::vec::Vec;
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    pub use alloc_crate::string::String;
    extern crate alloc as alloc_crate;
    pub use alloc_crate::alloc;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_messaging_provider_email_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*::
        exports::greentic::provider_schema_core::schema_core_api::__export_greentic_provider_schema_core_schema_core_api_1_0_0_cabi!($ty
        with_types_in $($path_to_types_root)*::
        exports::greentic::provider_schema_core::schema_core_api);
    };
}
#[doc(inline)]
pub(crate) use __export_messaging_provider_email_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:greentic:messaging-provider-email-core@0.0.1:messaging-provider-email:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 464] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xc1\x02\x01A\x02\x01\
A\x02\x01B\x0f\x01p}\x04\0\x11validation-result\x03\0\0\x01p}\x04\0\x0dhealth-st\
atus\x03\0\x02\x01p}\x04\0\x0dinvoke-result\x03\0\x04\x01p}\x01@\0\0\x06\x04\0\x08\
describe\x01\x07\x01@\x01\x0bconfig-json\x06\0\x01\x04\0\x0fvalidate-config\x01\x08\
\x01@\0\0\x03\x04\0\x0bhealthcheck\x01\x09\x01@\x02\x02ops\x0ainput-json\x06\0\x05\
\x04\0\x06invoke\x01\x0a\x04\03greentic:provider-schema-core/schema-core-api@1.0\
.0\x05\0\x04\0Egreentic:messaging-provider-email-core/messaging-provider-email@0\
.0.1\x04\0\x0b\x1e\x01\0\x18messaging-provider-email\x03\0\0\0G\x09producers\x01\
\x0cprocessed-by\x02\x0dwit-component\x070.227.1\x10wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
