// SPDX-License-Identifier: MIT

package greentic:messaging-ingress-teams@0.0.1;

use greentic:http/client@1.1.0 as http-client;
use greentic:secrets-store/secrets-store@1.0.0;
use greentic:state/state-store@1.0.0;
use greentic:telemetry/logger-api@1.0.0;
use provider:common/ingress@0.0.2;
use provider:common/subscriptions@0.0.2;

world messaging-ingress-teams {
    import http-client;
    import secrets-store;
    import state-store;
    import logger-api;

    export ingress;
    export subscriptions;
}
