// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
pub type Json = _rt::String;
/// Captures tenant-scoped identity and request affordances.
#[derive(Clone)]
pub struct TenantCtx {
    pub tenant: _rt::String,
    pub team: Option<_rt::String>,
    pub user: Option<_rt::String>,
    pub trace_id: Option<_rt::String>,
    pub i18n_id: Option<_rt::String>,
    pub correlation_id: Option<_rt::String>,
    pub deadline_unix_ms: Option<u64>,
    pub attempt: u32,
    pub idempotency_key: Option<_rt::String>,
}
impl ::core::fmt::Debug for TenantCtx {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("TenantCtx")
            .field("tenant", &self.tenant)
            .field("team", &self.team)
            .field("user", &self.user)
            .field("trace-id", &self.trace_id)
            .field("i18n-id", &self.i18n_id)
            .field("correlation-id", &self.correlation_id)
            .field("deadline-unix-ms", &self.deadline_unix_ms)
            .field("attempt", &self.attempt)
            .field("idempotency-key", &self.idempotency_key)
            .finish()
    }
}
/// Provides execution context for a single flow node invocation.
#[derive(Clone)]
pub struct ExecCtx {
    pub tenant: TenantCtx,
    pub i18n_id: Option<_rt::String>,
    pub flow_id: _rt::String,
    pub node_id: Option<_rt::String>,
}
impl ::core::fmt::Debug for ExecCtx {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("ExecCtx")
            .field("tenant", &self.tenant)
            .field("i18n-id", &self.i18n_id)
            .field("flow-id", &self.flow_id)
            .field("node-id", &self.node_id)
            .finish()
    }
}
/// A structured error code propagated back to the orchestrator.
#[derive(Clone)]
pub struct NodeError {
    pub code: _rt::String,
    pub message: _rt::String,
    pub retryable: bool,
    pub backoff_ms: Option<u64>,
    pub details: Option<Json>,
}
impl ::core::fmt::Debug for NodeError {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("NodeError")
            .field("code", &self.code)
            .field("message", &self.message)
            .field("retryable", &self.retryable)
            .field("backoff-ms", &self.backoff_ms)
            .field("details", &self.details)
            .finish()
    }
}
/// Result of an invoke operation.
#[derive(Clone)]
pub enum InvokeResult {
    Ok(Json),
    Err(NodeError),
}
impl ::core::fmt::Debug for InvokeResult {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        match self {
            InvokeResult::Ok(e) => f.debug_tuple("InvokeResult::Ok").field(e).finish(),
            InvokeResult::Err(e) => f.debug_tuple("InvokeResult::Err").field(e).finish(),
        }
    }
}
/// Streaming events emitted when executing invoke-stream.
#[derive(Clone)]
pub enum StreamEvent {
    Data(Json),
    Progress(u8),
    Done,
    Error(_rt::String),
}
impl ::core::fmt::Debug for StreamEvent {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        match self {
            StreamEvent::Data(e) => f.debug_tuple("StreamEvent::Data").field(e).finish(),
            StreamEvent::Progress(e) => {
                f.debug_tuple("StreamEvent::Progress").field(e).finish()
            }
            StreamEvent::Done => f.debug_tuple("StreamEvent::Done").finish(),
            StreamEvent::Error(e) => {
                f.debug_tuple("StreamEvent::Error").field(e).finish()
            }
        }
    }
}
/// Signals lifecycle success without carrying additional data.
#[repr(u8)]
#[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
pub enum LifecycleStatus {
    Ok,
}
impl ::core::fmt::Debug for LifecycleStatus {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        match self {
            LifecycleStatus::Ok => f.debug_tuple("LifecycleStatus::Ok").finish(),
        }
    }
}
impl LifecycleStatus {
    #[doc(hidden)]
    pub unsafe fn _lift(val: u8) -> LifecycleStatus {
        if !cfg!(debug_assertions) {
            return ::core::mem::transmute(val);
        }
        match val {
            0 => LifecycleStatus::Ok,
            _ => panic!("invalid enum discriminant"),
        }
    }
}
/// Layout preference for rendered results.
#[repr(u8)]
#[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
pub enum DisplayMode {
    Stacked,
    Grid,
}
impl ::core::fmt::Debug for DisplayMode {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        match self {
            DisplayMode::Stacked => f.debug_tuple("DisplayMode::Stacked").finish(),
            DisplayMode::Grid => f.debug_tuple("DisplayMode::Grid").finish(),
        }
    }
}
impl DisplayMode {
    #[doc(hidden)]
    pub unsafe fn _lift(val: u8) -> DisplayMode {
        if !cfg!(debug_assertions) {
            return ::core::mem::transmute(val);
        }
        match val {
            0 => DisplayMode::Stacked,
            1 => DisplayMode::Grid,
            _ => panic!("invalid enum discriminant"),
        }
    }
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_get_manifest_cabi<T: Guest>() -> *mut u8 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let result0 = T::get_manifest();
    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
    let vec2 = (result0.into_bytes()).into_boxed_slice();
    let ptr2 = vec2.as_ptr().cast::<u8>();
    let len2 = vec2.len();
    ::core::mem::forget(vec2);
    *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len2;
    *ptr1.add(0).cast::<*mut u8>() = ptr2.cast_mut();
    ptr1
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_get_manifest<T: Guest>(arg0: *mut u8) {
    let l0 = *arg0.add(0).cast::<*mut u8>();
    let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
    _rt::cabi_dealloc(l0, l1, 1);
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_on_start_cabi<T: Guest>(arg0: *mut u8) -> *mut u8 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let l0 = *arg0.add(0).cast::<*mut u8>();
    let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
    let len2 = l1;
    let bytes2 = _rt::Vec::from_raw_parts(l0.cast(), len2, len2);
    let l3 = i32::from(*arg0.add(2 * ::core::mem::size_of::<*const u8>()).cast::<u8>());
    let l7 = i32::from(*arg0.add(5 * ::core::mem::size_of::<*const u8>()).cast::<u8>());
    let l11 = i32::from(*arg0.add(8 * ::core::mem::size_of::<*const u8>()).cast::<u8>());
    let l15 = i32::from(
        *arg0.add(11 * ::core::mem::size_of::<*const u8>()).cast::<u8>(),
    );
    let l19 = i32::from(
        *arg0.add(14 * ::core::mem::size_of::<*const u8>()).cast::<u8>(),
    );
    let l23 = i32::from(
        *arg0.add(8 + 16 * ::core::mem::size_of::<*const u8>()).cast::<u8>(),
    );
    let l25 = *arg0.add(24 + 16 * ::core::mem::size_of::<*const u8>()).cast::<i32>();
    let l26 = i32::from(
        *arg0.add(24 + 17 * ::core::mem::size_of::<*const u8>()).cast::<u8>(),
    );
    let l30 = i32::from(
        *arg0.add(24 + 20 * ::core::mem::size_of::<*const u8>()).cast::<u8>(),
    );
    let l34 = *arg0.add(24 + 23 * ::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
    let l35 = *arg0.add(24 + 24 * ::core::mem::size_of::<*const u8>()).cast::<usize>();
    let len36 = l35;
    let bytes36 = _rt::Vec::from_raw_parts(l34.cast(), len36, len36);
    let l37 = i32::from(
        *arg0.add(24 + 25 * ::core::mem::size_of::<*const u8>()).cast::<u8>(),
    );
    let result41 = T::on_start(ExecCtx {
        tenant: TenantCtx {
            tenant: _rt::string_lift(bytes2),
            team: match l3 {
                0 => None,
                1 => {
                    let e = {
                        let l4 = *arg0
                            .add(3 * ::core::mem::size_of::<*const u8>())
                            .cast::<*mut u8>();
                        let l5 = *arg0
                            .add(4 * ::core::mem::size_of::<*const u8>())
                            .cast::<usize>();
                        let len6 = l5;
                        let bytes6 = _rt::Vec::from_raw_parts(l4.cast(), len6, len6);
                        _rt::string_lift(bytes6)
                    };
                    Some(e)
                }
                _ => _rt::invalid_enum_discriminant(),
            },
            user: match l7 {
                0 => None,
                1 => {
                    let e = {
                        let l8 = *arg0
                            .add(6 * ::core::mem::size_of::<*const u8>())
                            .cast::<*mut u8>();
                        let l9 = *arg0
                            .add(7 * ::core::mem::size_of::<*const u8>())
                            .cast::<usize>();
                        let len10 = l9;
                        let bytes10 = _rt::Vec::from_raw_parts(l8.cast(), len10, len10);
                        _rt::string_lift(bytes10)
                    };
                    Some(e)
                }
                _ => _rt::invalid_enum_discriminant(),
            },
            trace_id: match l11 {
                0 => None,
                1 => {
                    let e = {
                        let l12 = *arg0
                            .add(9 * ::core::mem::size_of::<*const u8>())
                            .cast::<*mut u8>();
                        let l13 = *arg0
                            .add(10 * ::core::mem::size_of::<*const u8>())
                            .cast::<usize>();
                        let len14 = l13;
                        let bytes14 = _rt::Vec::from_raw_parts(l12.cast(), len14, len14);
                        _rt::string_lift(bytes14)
                    };
                    Some(e)
                }
                _ => _rt::invalid_enum_discriminant(),
            },
            i18n_id: match l15 {
                0 => None,
                1 => {
                    let e = {
                        let l16 = *arg0
                            .add(12 * ::core::mem::size_of::<*const u8>())
                            .cast::<*mut u8>();
                        let l17 = *arg0
                            .add(13 * ::core::mem::size_of::<*const u8>())
                            .cast::<usize>();
                        let len18 = l17;
                        let bytes18 = _rt::Vec::from_raw_parts(l16.cast(), len18, len18);
                        _rt::string_lift(bytes18)
                    };
                    Some(e)
                }
                _ => _rt::invalid_enum_discriminant(),
            },
            correlation_id: match l19 {
                0 => None,
                1 => {
                    let e = {
                        let l20 = *arg0
                            .add(15 * ::core::mem::size_of::<*const u8>())
                            .cast::<*mut u8>();
                        let l21 = *arg0
                            .add(16 * ::core::mem::size_of::<*const u8>())
                            .cast::<usize>();
                        let len22 = l21;
                        let bytes22 = _rt::Vec::from_raw_parts(l20.cast(), len22, len22);
                        _rt::string_lift(bytes22)
                    };
                    Some(e)
                }
                _ => _rt::invalid_enum_discriminant(),
            },
            deadline_unix_ms: match l23 {
                0 => None,
                1 => {
                    let e = {
                        let l24 = *arg0
                            .add(16 + 16 * ::core::mem::size_of::<*const u8>())
                            .cast::<i64>();
                        l24 as u64
                    };
                    Some(e)
                }
                _ => _rt::invalid_enum_discriminant(),
            },
            attempt: l25 as u32,
            idempotency_key: match l26 {
                0 => None,
                1 => {
                    let e = {
                        let l27 = *arg0
                            .add(24 + 18 * ::core::mem::size_of::<*const u8>())
                            .cast::<*mut u8>();
                        let l28 = *arg0
                            .add(24 + 19 * ::core::mem::size_of::<*const u8>())
                            .cast::<usize>();
                        let len29 = l28;
                        let bytes29 = _rt::Vec::from_raw_parts(l27.cast(), len29, len29);
                        _rt::string_lift(bytes29)
                    };
                    Some(e)
                }
                _ => _rt::invalid_enum_discriminant(),
            },
        },
        i18n_id: match l30 {
            0 => None,
            1 => {
                let e = {
                    let l31 = *arg0
                        .add(24 + 21 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l32 = *arg0
                        .add(24 + 22 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let len33 = l32;
                    let bytes33 = _rt::Vec::from_raw_parts(l31.cast(), len33, len33);
                    _rt::string_lift(bytes33)
                };
                Some(e)
            }
            _ => _rt::invalid_enum_discriminant(),
        },
        flow_id: _rt::string_lift(bytes36),
        node_id: match l37 {
            0 => None,
            1 => {
                let e = {
                    let l38 = *arg0
                        .add(24 + 26 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l39 = *arg0
                        .add(24 + 27 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let len40 = l39;
                    let bytes40 = _rt::Vec::from_raw_parts(l38.cast(), len40, len40);
                    _rt::string_lift(bytes40)
                };
                Some(e)
            }
            _ => _rt::invalid_enum_discriminant(),
        },
    });
    _rt::cabi_dealloc(arg0, 24 + 28 * ::core::mem::size_of::<*const u8>(), 8);
    let ptr42 = (&raw mut _RET_AREA.0).cast::<u8>();
    match result41 {
        Ok(e) => {
            *ptr42.add(0).cast::<u8>() = (0i32) as u8;
            *ptr42.add(::core::mem::size_of::<*const u8>()).cast::<u8>() = (e.clone()
                as i32) as u8;
        }
        Err(e) => {
            *ptr42.add(0).cast::<u8>() = (1i32) as u8;
            let vec43 = (e.into_bytes()).into_boxed_slice();
            let ptr43 = vec43.as_ptr().cast::<u8>();
            let len43 = vec43.len();
            ::core::mem::forget(vec43);
            *ptr42.add(2 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len43;
            *ptr42.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr43
                .cast_mut();
        }
    };
    ptr42
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_on_start<T: Guest>(arg0: *mut u8) {
    let l0 = i32::from(*arg0.add(0).cast::<u8>());
    match l0 {
        0 => {}
        _ => {
            let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
            let l2 = *arg0.add(2 * ::core::mem::size_of::<*const u8>()).cast::<usize>();
            _rt::cabi_dealloc(l1, l2, 1);
        }
    }
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_on_stop_cabi<T: Guest>(arg0: *mut u8) -> *mut u8 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let l0 = *arg0.add(0).cast::<*mut u8>();
    let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
    let len2 = l1;
    let bytes2 = _rt::Vec::from_raw_parts(l0.cast(), len2, len2);
    let l3 = i32::from(*arg0.add(2 * ::core::mem::size_of::<*const u8>()).cast::<u8>());
    let l7 = i32::from(*arg0.add(5 * ::core::mem::size_of::<*const u8>()).cast::<u8>());
    let l11 = i32::from(*arg0.add(8 * ::core::mem::size_of::<*const u8>()).cast::<u8>());
    let l15 = i32::from(
        *arg0.add(11 * ::core::mem::size_of::<*const u8>()).cast::<u8>(),
    );
    let l19 = i32::from(
        *arg0.add(14 * ::core::mem::size_of::<*const u8>()).cast::<u8>(),
    );
    let l23 = i32::from(
        *arg0.add(8 + 16 * ::core::mem::size_of::<*const u8>()).cast::<u8>(),
    );
    let l25 = *arg0.add(24 + 16 * ::core::mem::size_of::<*const u8>()).cast::<i32>();
    let l26 = i32::from(
        *arg0.add(24 + 17 * ::core::mem::size_of::<*const u8>()).cast::<u8>(),
    );
    let l30 = i32::from(
        *arg0.add(24 + 20 * ::core::mem::size_of::<*const u8>()).cast::<u8>(),
    );
    let l34 = *arg0.add(24 + 23 * ::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
    let l35 = *arg0.add(24 + 24 * ::core::mem::size_of::<*const u8>()).cast::<usize>();
    let len36 = l35;
    let bytes36 = _rt::Vec::from_raw_parts(l34.cast(), len36, len36);
    let l37 = i32::from(
        *arg0.add(24 + 25 * ::core::mem::size_of::<*const u8>()).cast::<u8>(),
    );
    let l41 = *arg0.add(24 + 28 * ::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
    let l42 = *arg0.add(24 + 29 * ::core::mem::size_of::<*const u8>()).cast::<usize>();
    let len43 = l42;
    let bytes43 = _rt::Vec::from_raw_parts(l41.cast(), len43, len43);
    let result44 = T::on_stop(
        ExecCtx {
            tenant: TenantCtx {
                tenant: _rt::string_lift(bytes2),
                team: match l3 {
                    0 => None,
                    1 => {
                        let e = {
                            let l4 = *arg0
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l5 = *arg0
                                .add(4 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let len6 = l5;
                            let bytes6 = _rt::Vec::from_raw_parts(l4.cast(), len6, len6);
                            _rt::string_lift(bytes6)
                        };
                        Some(e)
                    }
                    _ => _rt::invalid_enum_discriminant(),
                },
                user: match l7 {
                    0 => None,
                    1 => {
                        let e = {
                            let l8 = *arg0
                                .add(6 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l9 = *arg0
                                .add(7 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let len10 = l9;
                            let bytes10 = _rt::Vec::from_raw_parts(
                                l8.cast(),
                                len10,
                                len10,
                            );
                            _rt::string_lift(bytes10)
                        };
                        Some(e)
                    }
                    _ => _rt::invalid_enum_discriminant(),
                },
                trace_id: match l11 {
                    0 => None,
                    1 => {
                        let e = {
                            let l12 = *arg0
                                .add(9 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l13 = *arg0
                                .add(10 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let len14 = l13;
                            let bytes14 = _rt::Vec::from_raw_parts(
                                l12.cast(),
                                len14,
                                len14,
                            );
                            _rt::string_lift(bytes14)
                        };
                        Some(e)
                    }
                    _ => _rt::invalid_enum_discriminant(),
                },
                i18n_id: match l15 {
                    0 => None,
                    1 => {
                        let e = {
                            let l16 = *arg0
                                .add(12 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l17 = *arg0
                                .add(13 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let len18 = l17;
                            let bytes18 = _rt::Vec::from_raw_parts(
                                l16.cast(),
                                len18,
                                len18,
                            );
                            _rt::string_lift(bytes18)
                        };
                        Some(e)
                    }
                    _ => _rt::invalid_enum_discriminant(),
                },
                correlation_id: match l19 {
                    0 => None,
                    1 => {
                        let e = {
                            let l20 = *arg0
                                .add(15 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l21 = *arg0
                                .add(16 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let len22 = l21;
                            let bytes22 = _rt::Vec::from_raw_parts(
                                l20.cast(),
                                len22,
                                len22,
                            );
                            _rt::string_lift(bytes22)
                        };
                        Some(e)
                    }
                    _ => _rt::invalid_enum_discriminant(),
                },
                deadline_unix_ms: match l23 {
                    0 => None,
                    1 => {
                        let e = {
                            let l24 = *arg0
                                .add(16 + 16 * ::core::mem::size_of::<*const u8>())
                                .cast::<i64>();
                            l24 as u64
                        };
                        Some(e)
                    }
                    _ => _rt::invalid_enum_discriminant(),
                },
                attempt: l25 as u32,
                idempotency_key: match l26 {
                    0 => None,
                    1 => {
                        let e = {
                            let l27 = *arg0
                                .add(24 + 18 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l28 = *arg0
                                .add(24 + 19 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let len29 = l28;
                            let bytes29 = _rt::Vec::from_raw_parts(
                                l27.cast(),
                                len29,
                                len29,
                            );
                            _rt::string_lift(bytes29)
                        };
                        Some(e)
                    }
                    _ => _rt::invalid_enum_discriminant(),
                },
            },
            i18n_id: match l30 {
                0 => None,
                1 => {
                    let e = {
                        let l31 = *arg0
                            .add(24 + 21 * ::core::mem::size_of::<*const u8>())
                            .cast::<*mut u8>();
                        let l32 = *arg0
                            .add(24 + 22 * ::core::mem::size_of::<*const u8>())
                            .cast::<usize>();
                        let len33 = l32;
                        let bytes33 = _rt::Vec::from_raw_parts(l31.cast(), len33, len33);
                        _rt::string_lift(bytes33)
                    };
                    Some(e)
                }
                _ => _rt::invalid_enum_discriminant(),
            },
            flow_id: _rt::string_lift(bytes36),
            node_id: match l37 {
                0 => None,
                1 => {
                    let e = {
                        let l38 = *arg0
                            .add(24 + 26 * ::core::mem::size_of::<*const u8>())
                            .cast::<*mut u8>();
                        let l39 = *arg0
                            .add(24 + 27 * ::core::mem::size_of::<*const u8>())
                            .cast::<usize>();
                        let len40 = l39;
                        let bytes40 = _rt::Vec::from_raw_parts(l38.cast(), len40, len40);
                        _rt::string_lift(bytes40)
                    };
                    Some(e)
                }
                _ => _rt::invalid_enum_discriminant(),
            },
        },
        _rt::string_lift(bytes43),
    );
    _rt::cabi_dealloc(arg0, 24 + 30 * ::core::mem::size_of::<*const u8>(), 8);
    let ptr45 = (&raw mut _RET_AREA.0).cast::<u8>();
    match result44 {
        Ok(e) => {
            *ptr45.add(0).cast::<u8>() = (0i32) as u8;
            *ptr45.add(::core::mem::size_of::<*const u8>()).cast::<u8>() = (e.clone()
                as i32) as u8;
        }
        Err(e) => {
            *ptr45.add(0).cast::<u8>() = (1i32) as u8;
            let vec46 = (e.into_bytes()).into_boxed_slice();
            let ptr46 = vec46.as_ptr().cast::<u8>();
            let len46 = vec46.len();
            ::core::mem::forget(vec46);
            *ptr45.add(2 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len46;
            *ptr45.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr46
                .cast_mut();
        }
    };
    ptr45
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_on_stop<T: Guest>(arg0: *mut u8) {
    let l0 = i32::from(*arg0.add(0).cast::<u8>());
    match l0 {
        0 => {}
        _ => {
            let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
            let l2 = *arg0.add(2 * ::core::mem::size_of::<*const u8>()).cast::<usize>();
            _rt::cabi_dealloc(l1, l2, 1);
        }
    }
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_invoke_cabi<T: Guest>(arg0: *mut u8) -> *mut u8 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let l0 = *arg0.add(0).cast::<*mut u8>();
    let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
    let len2 = l1;
    let bytes2 = _rt::Vec::from_raw_parts(l0.cast(), len2, len2);
    let l3 = i32::from(*arg0.add(2 * ::core::mem::size_of::<*const u8>()).cast::<u8>());
    let l7 = i32::from(*arg0.add(5 * ::core::mem::size_of::<*const u8>()).cast::<u8>());
    let l11 = i32::from(*arg0.add(8 * ::core::mem::size_of::<*const u8>()).cast::<u8>());
    let l15 = i32::from(
        *arg0.add(11 * ::core::mem::size_of::<*const u8>()).cast::<u8>(),
    );
    let l19 = i32::from(
        *arg0.add(14 * ::core::mem::size_of::<*const u8>()).cast::<u8>(),
    );
    let l23 = i32::from(
        *arg0.add(8 + 16 * ::core::mem::size_of::<*const u8>()).cast::<u8>(),
    );
    let l25 = *arg0.add(24 + 16 * ::core::mem::size_of::<*const u8>()).cast::<i32>();
    let l26 = i32::from(
        *arg0.add(24 + 17 * ::core::mem::size_of::<*const u8>()).cast::<u8>(),
    );
    let l30 = i32::from(
        *arg0.add(24 + 20 * ::core::mem::size_of::<*const u8>()).cast::<u8>(),
    );
    let l34 = *arg0.add(24 + 23 * ::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
    let l35 = *arg0.add(24 + 24 * ::core::mem::size_of::<*const u8>()).cast::<usize>();
    let len36 = l35;
    let bytes36 = _rt::Vec::from_raw_parts(l34.cast(), len36, len36);
    let l37 = i32::from(
        *arg0.add(24 + 25 * ::core::mem::size_of::<*const u8>()).cast::<u8>(),
    );
    let l41 = *arg0.add(24 + 28 * ::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
    let l42 = *arg0.add(24 + 29 * ::core::mem::size_of::<*const u8>()).cast::<usize>();
    let len43 = l42;
    let bytes43 = _rt::Vec::from_raw_parts(l41.cast(), len43, len43);
    let l44 = *arg0.add(24 + 30 * ::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
    let l45 = *arg0.add(24 + 31 * ::core::mem::size_of::<*const u8>()).cast::<usize>();
    let len46 = l45;
    let bytes46 = _rt::Vec::from_raw_parts(l44.cast(), len46, len46);
    let result47 = T::invoke(
        ExecCtx {
            tenant: TenantCtx {
                tenant: _rt::string_lift(bytes2),
                team: match l3 {
                    0 => None,
                    1 => {
                        let e = {
                            let l4 = *arg0
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l5 = *arg0
                                .add(4 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let len6 = l5;
                            let bytes6 = _rt::Vec::from_raw_parts(l4.cast(), len6, len6);
                            _rt::string_lift(bytes6)
                        };
                        Some(e)
                    }
                    _ => _rt::invalid_enum_discriminant(),
                },
                user: match l7 {
                    0 => None,
                    1 => {
                        let e = {
                            let l8 = *arg0
                                .add(6 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l9 = *arg0
                                .add(7 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let len10 = l9;
                            let bytes10 = _rt::Vec::from_raw_parts(
                                l8.cast(),
                                len10,
                                len10,
                            );
                            _rt::string_lift(bytes10)
                        };
                        Some(e)
                    }
                    _ => _rt::invalid_enum_discriminant(),
                },
                trace_id: match l11 {
                    0 => None,
                    1 => {
                        let e = {
                            let l12 = *arg0
                                .add(9 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l13 = *arg0
                                .add(10 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let len14 = l13;
                            let bytes14 = _rt::Vec::from_raw_parts(
                                l12.cast(),
                                len14,
                                len14,
                            );
                            _rt::string_lift(bytes14)
                        };
                        Some(e)
                    }
                    _ => _rt::invalid_enum_discriminant(),
                },
                i18n_id: match l15 {
                    0 => None,
                    1 => {
                        let e = {
                            let l16 = *arg0
                                .add(12 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l17 = *arg0
                                .add(13 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let len18 = l17;
                            let bytes18 = _rt::Vec::from_raw_parts(
                                l16.cast(),
                                len18,
                                len18,
                            );
                            _rt::string_lift(bytes18)
                        };
                        Some(e)
                    }
                    _ => _rt::invalid_enum_discriminant(),
                },
                correlation_id: match l19 {
                    0 => None,
                    1 => {
                        let e = {
                            let l20 = *arg0
                                .add(15 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l21 = *arg0
                                .add(16 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let len22 = l21;
                            let bytes22 = _rt::Vec::from_raw_parts(
                                l20.cast(),
                                len22,
                                len22,
                            );
                            _rt::string_lift(bytes22)
                        };
                        Some(e)
                    }
                    _ => _rt::invalid_enum_discriminant(),
                },
                deadline_unix_ms: match l23 {
                    0 => None,
                    1 => {
                        let e = {
                            let l24 = *arg0
                                .add(16 + 16 * ::core::mem::size_of::<*const u8>())
                                .cast::<i64>();
                            l24 as u64
                        };
                        Some(e)
                    }
                    _ => _rt::invalid_enum_discriminant(),
                },
                attempt: l25 as u32,
                idempotency_key: match l26 {
                    0 => None,
                    1 => {
                        let e = {
                            let l27 = *arg0
                                .add(24 + 18 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l28 = *arg0
                                .add(24 + 19 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let len29 = l28;
                            let bytes29 = _rt::Vec::from_raw_parts(
                                l27.cast(),
                                len29,
                                len29,
                            );
                            _rt::string_lift(bytes29)
                        };
                        Some(e)
                    }
                    _ => _rt::invalid_enum_discriminant(),
                },
            },
            i18n_id: match l30 {
                0 => None,
                1 => {
                    let e = {
                        let l31 = *arg0
                            .add(24 + 21 * ::core::mem::size_of::<*const u8>())
                            .cast::<*mut u8>();
                        let l32 = *arg0
                            .add(24 + 22 * ::core::mem::size_of::<*const u8>())
                            .cast::<usize>();
                        let len33 = l32;
                        let bytes33 = _rt::Vec::from_raw_parts(l31.cast(), len33, len33);
                        _rt::string_lift(bytes33)
                    };
                    Some(e)
                }
                _ => _rt::invalid_enum_discriminant(),
            },
            flow_id: _rt::string_lift(bytes36),
            node_id: match l37 {
                0 => None,
                1 => {
                    let e = {
                        let l38 = *arg0
                            .add(24 + 26 * ::core::mem::size_of::<*const u8>())
                            .cast::<*mut u8>();
                        let l39 = *arg0
                            .add(24 + 27 * ::core::mem::size_of::<*const u8>())
                            .cast::<usize>();
                        let len40 = l39;
                        let bytes40 = _rt::Vec::from_raw_parts(l38.cast(), len40, len40);
                        _rt::string_lift(bytes40)
                    };
                    Some(e)
                }
                _ => _rt::invalid_enum_discriminant(),
            },
        },
        _rt::string_lift(bytes43),
        _rt::string_lift(bytes46),
    );
    _rt::cabi_dealloc(arg0, 24 + 32 * ::core::mem::size_of::<*const u8>(), 8);
    let ptr48 = (&raw mut _RET_AREA.0).cast::<u8>();
    match result47 {
        InvokeResult::Ok(e) => {
            *ptr48.add(0).cast::<u8>() = (0i32) as u8;
            let vec49 = (e.into_bytes()).into_boxed_slice();
            let ptr49 = vec49.as_ptr().cast::<u8>();
            let len49 = vec49.len();
            ::core::mem::forget(vec49);
            *ptr48.add(8 + 1 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len49;
            *ptr48.add(8).cast::<*mut u8>() = ptr49.cast_mut();
        }
        InvokeResult::Err(e) => {
            *ptr48.add(0).cast::<u8>() = (1i32) as u8;
            let NodeError {
                code: code50,
                message: message50,
                retryable: retryable50,
                backoff_ms: backoff_ms50,
                details: details50,
            } = e;
            let vec51 = (code50.into_bytes()).into_boxed_slice();
            let ptr51 = vec51.as_ptr().cast::<u8>();
            let len51 = vec51.len();
            ::core::mem::forget(vec51);
            *ptr48.add(8 + 1 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len51;
            *ptr48.add(8).cast::<*mut u8>() = ptr51.cast_mut();
            let vec52 = (message50.into_bytes()).into_boxed_slice();
            let ptr52 = vec52.as_ptr().cast::<u8>();
            let len52 = vec52.len();
            ::core::mem::forget(vec52);
            *ptr48.add(8 + 3 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len52;
            *ptr48.add(8 + 2 * ::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr52
                .cast_mut();
            *ptr48.add(8 + 4 * ::core::mem::size_of::<*const u8>()).cast::<u8>() = (match retryable50 {
                true => 1,
                false => 0,
            }) as u8;
            match backoff_ms50 {
                Some(e) => {
                    *ptr48
                        .add(16 + 4 * ::core::mem::size_of::<*const u8>())
                        .cast::<u8>() = (1i32) as u8;
                    *ptr48
                        .add(24 + 4 * ::core::mem::size_of::<*const u8>())
                        .cast::<i64>() = _rt::as_i64(e);
                }
                None => {
                    *ptr48
                        .add(16 + 4 * ::core::mem::size_of::<*const u8>())
                        .cast::<u8>() = (0i32) as u8;
                }
            };
            match details50 {
                Some(e) => {
                    *ptr48
                        .add(32 + 4 * ::core::mem::size_of::<*const u8>())
                        .cast::<u8>() = (1i32) as u8;
                    let vec53 = (e.into_bytes()).into_boxed_slice();
                    let ptr53 = vec53.as_ptr().cast::<u8>();
                    let len53 = vec53.len();
                    ::core::mem::forget(vec53);
                    *ptr48
                        .add(32 + 6 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>() = len53;
                    *ptr48
                        .add(32 + 5 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>() = ptr53.cast_mut();
                }
                None => {
                    *ptr48
                        .add(32 + 4 * ::core::mem::size_of::<*const u8>())
                        .cast::<u8>() = (0i32) as u8;
                }
            };
        }
    }
    ptr48
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_invoke<T: Guest>(arg0: *mut u8) {
    let l0 = i32::from(*arg0.add(0).cast::<u8>());
    match l0 {
        0 => {
            let l1 = *arg0.add(8).cast::<*mut u8>();
            let l2 = *arg0
                .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                .cast::<usize>();
            _rt::cabi_dealloc(l1, l2, 1);
        }
        _ => {
            let l3 = *arg0.add(8).cast::<*mut u8>();
            let l4 = *arg0
                .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                .cast::<usize>();
            _rt::cabi_dealloc(l3, l4, 1);
            let l5 = *arg0
                .add(8 + 2 * ::core::mem::size_of::<*const u8>())
                .cast::<*mut u8>();
            let l6 = *arg0
                .add(8 + 3 * ::core::mem::size_of::<*const u8>())
                .cast::<usize>();
            _rt::cabi_dealloc(l5, l6, 1);
            let l7 = i32::from(
                *arg0.add(32 + 4 * ::core::mem::size_of::<*const u8>()).cast::<u8>(),
            );
            match l7 {
                0 => {}
                _ => {
                    let l8 = *arg0
                        .add(32 + 5 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l9 = *arg0
                        .add(32 + 6 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l8, l9, 1);
                }
            }
        }
    }
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_invoke_stream_cabi<T: Guest>(arg0: *mut u8) -> *mut u8 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let l0 = *arg0.add(0).cast::<*mut u8>();
    let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
    let len2 = l1;
    let bytes2 = _rt::Vec::from_raw_parts(l0.cast(), len2, len2);
    let l3 = i32::from(*arg0.add(2 * ::core::mem::size_of::<*const u8>()).cast::<u8>());
    let l7 = i32::from(*arg0.add(5 * ::core::mem::size_of::<*const u8>()).cast::<u8>());
    let l11 = i32::from(*arg0.add(8 * ::core::mem::size_of::<*const u8>()).cast::<u8>());
    let l15 = i32::from(
        *arg0.add(11 * ::core::mem::size_of::<*const u8>()).cast::<u8>(),
    );
    let l19 = i32::from(
        *arg0.add(14 * ::core::mem::size_of::<*const u8>()).cast::<u8>(),
    );
    let l23 = i32::from(
        *arg0.add(8 + 16 * ::core::mem::size_of::<*const u8>()).cast::<u8>(),
    );
    let l25 = *arg0.add(24 + 16 * ::core::mem::size_of::<*const u8>()).cast::<i32>();
    let l26 = i32::from(
        *arg0.add(24 + 17 * ::core::mem::size_of::<*const u8>()).cast::<u8>(),
    );
    let l30 = i32::from(
        *arg0.add(24 + 20 * ::core::mem::size_of::<*const u8>()).cast::<u8>(),
    );
    let l34 = *arg0.add(24 + 23 * ::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
    let l35 = *arg0.add(24 + 24 * ::core::mem::size_of::<*const u8>()).cast::<usize>();
    let len36 = l35;
    let bytes36 = _rt::Vec::from_raw_parts(l34.cast(), len36, len36);
    let l37 = i32::from(
        *arg0.add(24 + 25 * ::core::mem::size_of::<*const u8>()).cast::<u8>(),
    );
    let l41 = *arg0.add(24 + 28 * ::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
    let l42 = *arg0.add(24 + 29 * ::core::mem::size_of::<*const u8>()).cast::<usize>();
    let len43 = l42;
    let bytes43 = _rt::Vec::from_raw_parts(l41.cast(), len43, len43);
    let l44 = *arg0.add(24 + 30 * ::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
    let l45 = *arg0.add(24 + 31 * ::core::mem::size_of::<*const u8>()).cast::<usize>();
    let len46 = l45;
    let bytes46 = _rt::Vec::from_raw_parts(l44.cast(), len46, len46);
    let result47 = T::invoke_stream(
        ExecCtx {
            tenant: TenantCtx {
                tenant: _rt::string_lift(bytes2),
                team: match l3 {
                    0 => None,
                    1 => {
                        let e = {
                            let l4 = *arg0
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l5 = *arg0
                                .add(4 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let len6 = l5;
                            let bytes6 = _rt::Vec::from_raw_parts(l4.cast(), len6, len6);
                            _rt::string_lift(bytes6)
                        };
                        Some(e)
                    }
                    _ => _rt::invalid_enum_discriminant(),
                },
                user: match l7 {
                    0 => None,
                    1 => {
                        let e = {
                            let l8 = *arg0
                                .add(6 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l9 = *arg0
                                .add(7 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let len10 = l9;
                            let bytes10 = _rt::Vec::from_raw_parts(
                                l8.cast(),
                                len10,
                                len10,
                            );
                            _rt::string_lift(bytes10)
                        };
                        Some(e)
                    }
                    _ => _rt::invalid_enum_discriminant(),
                },
                trace_id: match l11 {
                    0 => None,
                    1 => {
                        let e = {
                            let l12 = *arg0
                                .add(9 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l13 = *arg0
                                .add(10 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let len14 = l13;
                            let bytes14 = _rt::Vec::from_raw_parts(
                                l12.cast(),
                                len14,
                                len14,
                            );
                            _rt::string_lift(bytes14)
                        };
                        Some(e)
                    }
                    _ => _rt::invalid_enum_discriminant(),
                },
                i18n_id: match l15 {
                    0 => None,
                    1 => {
                        let e = {
                            let l16 = *arg0
                                .add(12 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l17 = *arg0
                                .add(13 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let len18 = l17;
                            let bytes18 = _rt::Vec::from_raw_parts(
                                l16.cast(),
                                len18,
                                len18,
                            );
                            _rt::string_lift(bytes18)
                        };
                        Some(e)
                    }
                    _ => _rt::invalid_enum_discriminant(),
                },
                correlation_id: match l19 {
                    0 => None,
                    1 => {
                        let e = {
                            let l20 = *arg0
                                .add(15 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l21 = *arg0
                                .add(16 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let len22 = l21;
                            let bytes22 = _rt::Vec::from_raw_parts(
                                l20.cast(),
                                len22,
                                len22,
                            );
                            _rt::string_lift(bytes22)
                        };
                        Some(e)
                    }
                    _ => _rt::invalid_enum_discriminant(),
                },
                deadline_unix_ms: match l23 {
                    0 => None,
                    1 => {
                        let e = {
                            let l24 = *arg0
                                .add(16 + 16 * ::core::mem::size_of::<*const u8>())
                                .cast::<i64>();
                            l24 as u64
                        };
                        Some(e)
                    }
                    _ => _rt::invalid_enum_discriminant(),
                },
                attempt: l25 as u32,
                idempotency_key: match l26 {
                    0 => None,
                    1 => {
                        let e = {
                            let l27 = *arg0
                                .add(24 + 18 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l28 = *arg0
                                .add(24 + 19 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let len29 = l28;
                            let bytes29 = _rt::Vec::from_raw_parts(
                                l27.cast(),
                                len29,
                                len29,
                            );
                            _rt::string_lift(bytes29)
                        };
                        Some(e)
                    }
                    _ => _rt::invalid_enum_discriminant(),
                },
            },
            i18n_id: match l30 {
                0 => None,
                1 => {
                    let e = {
                        let l31 = *arg0
                            .add(24 + 21 * ::core::mem::size_of::<*const u8>())
                            .cast::<*mut u8>();
                        let l32 = *arg0
                            .add(24 + 22 * ::core::mem::size_of::<*const u8>())
                            .cast::<usize>();
                        let len33 = l32;
                        let bytes33 = _rt::Vec::from_raw_parts(l31.cast(), len33, len33);
                        _rt::string_lift(bytes33)
                    };
                    Some(e)
                }
                _ => _rt::invalid_enum_discriminant(),
            },
            flow_id: _rt::string_lift(bytes36),
            node_id: match l37 {
                0 => None,
                1 => {
                    let e = {
                        let l38 = *arg0
                            .add(24 + 26 * ::core::mem::size_of::<*const u8>())
                            .cast::<*mut u8>();
                        let l39 = *arg0
                            .add(24 + 27 * ::core::mem::size_of::<*const u8>())
                            .cast::<usize>();
                        let len40 = l39;
                        let bytes40 = _rt::Vec::from_raw_parts(l38.cast(), len40, len40);
                        _rt::string_lift(bytes40)
                    };
                    Some(e)
                }
                _ => _rt::invalid_enum_discriminant(),
            },
        },
        _rt::string_lift(bytes43),
        _rt::string_lift(bytes46),
    );
    _rt::cabi_dealloc(arg0, 24 + 32 * ::core::mem::size_of::<*const u8>(), 8);
    let ptr48 = (&raw mut _RET_AREA.0).cast::<u8>();
    let vec51 = result47;
    let len51 = vec51.len();
    let layout51 = _rt::alloc::Layout::from_size_align_unchecked(
        vec51.len() * (3 * ::core::mem::size_of::<*const u8>()),
        ::core::mem::size_of::<*const u8>(),
    );
    let result51 = if layout51.size() != 0 {
        let ptr = _rt::alloc::alloc(layout51).cast::<u8>();
        if ptr.is_null() {
            _rt::alloc::handle_alloc_error(layout51);
        }
        ptr
    } else {
        ::core::ptr::null_mut()
    };
    for (i, e) in vec51.into_iter().enumerate() {
        let base = result51.add(i * (3 * ::core::mem::size_of::<*const u8>()));
        {
            match e {
                StreamEvent::Data(e) => {
                    *base.add(0).cast::<u8>() = (0i32) as u8;
                    let vec49 = (e.into_bytes()).into_boxed_slice();
                    let ptr49 = vec49.as_ptr().cast::<u8>();
                    let len49 = vec49.len();
                    ::core::mem::forget(vec49);
                    *base.add(2 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len49;
                    *base.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr49
                        .cast_mut();
                }
                StreamEvent::Progress(e) => {
                    *base.add(0).cast::<u8>() = (1i32) as u8;
                    *base.add(::core::mem::size_of::<*const u8>()).cast::<u8>() = (_rt::as_i32(
                        e,
                    )) as u8;
                }
                StreamEvent::Done => {
                    *base.add(0).cast::<u8>() = (2i32) as u8;
                }
                StreamEvent::Error(e) => {
                    *base.add(0).cast::<u8>() = (3i32) as u8;
                    let vec50 = (e.into_bytes()).into_boxed_slice();
                    let ptr50 = vec50.as_ptr().cast::<u8>();
                    let len50 = vec50.len();
                    ::core::mem::forget(vec50);
                    *base.add(2 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len50;
                    *base.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr50
                        .cast_mut();
                }
            }
        }
    }
    *ptr48.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len51;
    *ptr48.add(0).cast::<*mut u8>() = result51;
    ptr48
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_invoke_stream<T: Guest>(arg0: *mut u8) {
    let l0 = *arg0.add(0).cast::<*mut u8>();
    let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
    let base7 = l0;
    let len7 = l1;
    for i in 0..len7 {
        let base = base7.add(i * (3 * ::core::mem::size_of::<*const u8>()));
        {
            let l2 = i32::from(*base.add(0).cast::<u8>());
            match l2 {
                0 => {
                    let l3 = *base
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l4 = *base
                        .add(2 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l3, l4, 1);
                }
                1 => {}
                2 => {}
                _ => {
                    let l5 = *base
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l6 = *base
                        .add(2 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l5, l6, 1);
                }
            }
        }
    }
    _rt::cabi_dealloc(
        base7,
        len7 * (3 * ::core::mem::size_of::<*const u8>()),
        ::core::mem::size_of::<*const u8>(),
    );
}
pub trait Guest {
    /// Returns a JSON manifest describing the component's capabilities.
    fn get_manifest() -> Json;
    /// Optional lifecycle hook when the component starts.
    fn on_start(ctx: ExecCtx) -> Result<LifecycleStatus, _rt::String>;
    /// Optional lifecycle hook when the component stops.
    fn on_stop(
        ctx: ExecCtx,
        reason: _rt::String,
    ) -> Result<LifecycleStatus, _rt::String>;
    /// Invokes an operation with execution context and JSON payload.
    fn invoke(ctx: ExecCtx, op: _rt::String, input: Json) -> InvokeResult;
    /// Invokes an operation that emits a bounded list of streaming events.
    fn invoke_stream(
        ctx: ExecCtx,
        op: _rt::String,
        input: Json,
    ) -> _rt::Vec<StreamEvent>;
}
#[doc(hidden)]
macro_rules! __export_world_node_cabi {
    ($ty:ident with_types_in $($path_to_types:tt)*) => {
        const _ : () = { #[unsafe (export_name = "get-manifest")] unsafe extern "C" fn
        export_get_manifest() -> * mut u8 { unsafe { $($path_to_types)*::
        _export_get_manifest_cabi::<$ty > () } } #[unsafe (export_name =
        "cabi_post_get-manifest")] unsafe extern "C" fn _post_return_get_manifest(arg0 :
        * mut u8,) { unsafe { $($path_to_types)*:: __post_return_get_manifest::<$ty >
        (arg0) } } #[unsafe (export_name = "on-start")] unsafe extern "C" fn
        export_on_start(arg0 : * mut u8,) -> * mut u8 { unsafe { $($path_to_types)*::
        _export_on_start_cabi::<$ty > (arg0) } } #[unsafe (export_name =
        "cabi_post_on-start")] unsafe extern "C" fn _post_return_on_start(arg0 : * mut
        u8,) { unsafe { $($path_to_types)*:: __post_return_on_start::<$ty > (arg0) } }
        #[unsafe (export_name = "on-stop")] unsafe extern "C" fn export_on_stop(arg0 : *
        mut u8,) -> * mut u8 { unsafe { $($path_to_types)*:: _export_on_stop_cabi::<$ty >
        (arg0) } } #[unsafe (export_name = "cabi_post_on-stop")] unsafe extern "C" fn
        _post_return_on_stop(arg0 : * mut u8,) { unsafe { $($path_to_types)*::
        __post_return_on_stop::<$ty > (arg0) } } #[unsafe (export_name = "invoke")]
        unsafe extern "C" fn export_invoke(arg0 : * mut u8,) -> * mut u8 { unsafe {
        $($path_to_types)*:: _export_invoke_cabi::<$ty > (arg0) } } #[unsafe (export_name
        = "cabi_post_invoke")] unsafe extern "C" fn _post_return_invoke(arg0 : * mut u8,)
        { unsafe { $($path_to_types)*:: __post_return_invoke::<$ty > (arg0) } } #[unsafe
        (export_name = "invoke-stream")] unsafe extern "C" fn export_invoke_stream(arg0 :
        * mut u8,) -> * mut u8 { unsafe { $($path_to_types)*::
        _export_invoke_stream_cabi::<$ty > (arg0) } } #[unsafe (export_name =
        "cabi_post_invoke-stream")] unsafe extern "C" fn _post_return_invoke_stream(arg0
        : * mut u8,) { unsafe { $($path_to_types)*:: __post_return_invoke_stream::<$ty >
        (arg0) } } };
    };
}
#[doc(hidden)]
pub(crate) use __export_world_node_cabi;
#[repr(align(8))]
struct _RetArea(
    [::core::mem::MaybeUninit<u8>; 40 + 6 * ::core::mem::size_of::<*const u8>()],
);
static mut _RET_AREA: _RetArea = _RetArea(
    [::core::mem::MaybeUninit::uninit(); 40 + 6 * ::core::mem::size_of::<*const u8>()],
);
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod greentic {
    pub mod component {
        /// Cooperative control-plane hooks surfaced to components.
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod control {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            #[allow(unused_unsafe, clippy::all)]
            /// Returns true when the host requests cancellation.
            pub fn should_cancel() -> bool {
                unsafe {
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "greentic:component/control@0.5.0")]
                    unsafe extern "C" {
                        #[link_name = "should-cancel"]
                        fn wit_import0() -> i32;
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import0() -> i32 {
                        unreachable!()
                    }
                    let ret = unsafe { wit_import0() };
                    _rt::bool_lift(ret as u8)
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            /// Yields execution back to the host.
            pub fn yield_now() -> () {
                unsafe {
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "greentic:component/control@0.5.0")]
                    unsafe extern "C" {
                        #[link_name = "yield-now"]
                        fn wit_import0();
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import0() {
                        unreachable!()
                    }
                    unsafe { wit_import0() };
                }
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    pub unsafe fn bool_lift(val: u8) -> bool {
        if cfg!(debug_assertions) {
            match val {
                0 => false,
                1 => true,
                _ => panic!("invalid bool discriminant"),
            }
        } else {
            val != 0
        }
    }
    pub use alloc_crate::string::String;
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    pub use alloc_crate::vec::Vec;
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    pub unsafe fn invalid_enum_discriminant<T>() -> T {
        if cfg!(debug_assertions) {
            panic!("invalid enum discriminant")
        } else {
            unsafe { core::hint::unreachable_unchecked() }
        }
    }
    pub fn as_i64<T: AsI64>(t: T) -> i64 {
        t.as_i64()
    }
    pub trait AsI64 {
        fn as_i64(self) -> i64;
    }
    impl<'a, T: Copy + AsI64> AsI64 for &'a T {
        fn as_i64(self) -> i64 {
            (*self).as_i64()
        }
    }
    impl AsI64 for i64 {
        #[inline]
        fn as_i64(self) -> i64 {
            self as i64
        }
    }
    impl AsI64 for u64 {
        #[inline]
        fn as_i64(self) -> i64 {
            self as i64
        }
    }
    pub fn as_i32<T: AsI32>(t: T) -> i32 {
        t.as_i32()
    }
    pub trait AsI32 {
        fn as_i32(self) -> i32;
    }
    impl<'a, T: Copy + AsI32> AsI32 for &'a T {
        fn as_i32(self) -> i32 {
            (*self).as_i32()
        }
    }
    impl AsI32 for i32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for char {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for usize {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    pub use alloc_crate::alloc;
    extern crate alloc as alloc_crate;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_node_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*:: __export_world_node_cabi!($ty with_types_in
        $($path_to_types_root)*);
    };
}
#[doc(inline)]
pub(crate) use __export_node_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:greentic:component@0.5.0:node:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 892] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\x81\x06\x01A\x02\x01\
A%\x01s\x03\0\x04json\x03\0\0\x01ks\x01kw\x01r\x09\x06tenants\x04team\x02\x04use\
r\x02\x08trace-id\x02\x07i18n-id\x02\x0ecorrelation-id\x02\x10deadline-unix-ms\x03\
\x07attempty\x0fidempotency-key\x02\x03\0\x0atenant-ctx\x03\0\x04\x01r\x04\x06te\
nant\x05\x07i18n-id\x02\x07flow-ids\x07node-id\x02\x03\0\x08exec-ctx\x03\0\x06\x01\
k\x01\x01r\x05\x04codes\x07messages\x09retryable\x7f\x0abackoff-ms\x03\x07detail\
s\x08\x03\0\x0anode-error\x03\0\x09\x01q\x02\x02ok\x01\x01\0\x03err\x01\x0a\0\x03\
\0\x0dinvoke-result\x03\0\x0b\x01q\x04\x04data\x01\x01\0\x08progress\x01}\0\x04d\
one\0\0\x05error\x01s\0\x03\0\x0cstream-event\x03\0\x0d\x01m\x01\x02ok\x03\0\x10\
lifecycle-status\x03\0\x0f\x01m\x02\x07stacked\x04grid\x03\0\x0cdisplay-mode\x03\
\0\x11\x01ps\x01k\x13\x01r\x06\x05titles\x0bdescription\x02\x06layout\x12\x09max\
-itemsy\x04tags\x14\x0dconnection-id\x02\x03\0\x06config\x03\0\x15\x01B\x04\x01@\
\0\0\x7f\x04\0\x0dshould-cancel\x01\0\x01@\0\x01\0\x04\0\x09yield-now\x01\x01\x03\
\0\x20greentic:component/control@0.5.0\x05\x17\x01@\0\0\x01\x04\0\x0cget-manifes\
t\x01\x18\x01j\x01\x10\x01s\x01@\x01\x03ctx\x07\0\x19\x04\0\x08on-start\x01\x1a\x01\
@\x02\x03ctx\x07\x06reasons\0\x19\x04\0\x07on-stop\x01\x1b\x01@\x03\x03ctx\x07\x02\
ops\x05input\x01\0\x0c\x04\0\x06invoke\x01\x1c\x01p\x0e\x01@\x03\x03ctx\x07\x02o\
ps\x05input\x01\0\x1d\x04\0\x0dinvoke-stream\x01\x1e\x04\0\x1dgreentic:component\
/node@0.5.0\x04\0\x0b\x0a\x01\0\x04node\x03\0\0\0G\x09producers\x01\x0cprocessed\
-by\x02\x0dwit-component\x070.227.1\x10wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
